export enum runTypes {
    BEGIN_RUN = 'BEGIN_RUN',
    FETCH_USER_RUNS = 'FETCH_USER_RUNS',
    DELETE_RUN = 'DELETE_RUN',
    FETCH_CURRENT_RUN = 'FETCH_CURRENT_RUN',
    FETCH_RUN_DETAILS = 'FETCH_RUN_DETAILS',
    END_RUN = 'END_RUN',
    SET_RUNS = 'SET_RUNS',
    CLEAR_CURRENT_RUN = 'CLEAR_CURRENT_RUN',
    SET_RUN_DETAILS = 'SET_RUN_DETAILS',
    SET_CURRENT_RUN = 'SET_CURRENT_RUN',

}
