export enum treatmentTypes {
    FETCH_TREATMENTS = 'FETCH_TREATMENTS',
    ADD_TX_EVENT = 'ADD_TX_EVENT',
    FETCH_CURRENT_TREATMENT = 'FETCH_CURRENT_TREATMENT',
    DELETE_TREATMENT = 'DELETE_TREATMENT',
    FETCH_ALL_TREATMENTS = 'FETCH_ALL_TREATMENTS',
    EDIT_TX = 'EDIT_TX',
    SET_ALL_TREATMENTS = 'SET_ALL_TREATMENTS',
    SET_CURRENT_TREATMENT = 'SET_CURRENT_TREATMENT',
    SET_TREATMENTS = 'SET_TREATMENTS'
}